### ISSUE TITLE
lg_infrared: button.press fails with 'int' object has no attribute 'high_us' after 2026.5 upgrade

### ISSUE THREAD

**Issue by ElBalsero** [JackJPowell/hass-unfoldedcircle#164]
**Describe the bug**
Version 1.1.0 came prepared to work with the new infrared platform in Home Assistant 2026.4. That worked well. However, 2026.5 seems to have introduced a breaking change.

**To Reproduce**
You need do install HA 2026.5 and have the infrared platform configured. In my case, as LG_Infrared
Any button press will result in an error saying: “ Error 'int' object has no attribute 'high_us'”

**Expected behavior**
It should send the IR command without errors as it did in 2026.4

**Screenshots**

2026-05-26 02:15:42.078 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140130744968000] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 279, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2827, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2870, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 951, in entity_service_call
    response_data = await _async_handle_entity_calls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 830, in _async_handle_entity_calls
    single_result = await entity.async_request_call(_with_context(entity, coro))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1696, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 825, in _with_context
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 909, in _handle_single_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 132, in _async_press_action
    await self.async_press()
  File "/usr/src/homeassistant/homeassistant/components/lg_infrared/button.py", line 147, in async_press
    await self._send_command(self.entity_description.command_code)
  File "/usr/src/homeassistant/homeassistant/components/lg_infrared/entity.py", line 71, in _send_command
    await async_send_command(
    ...<4 lines>...
    )
  File "/usr/src/homeassistant/homeassistant/components/infrared/__init__.py", line 104, in async_send_command
    await entity.async_send_command_internal(command)
  File "/usr/src/homeassistant/homeassistant/components/infrared/__init__.py", line 132, in async_send_command_internal
    await self.async_send_command(command)
  File "/config/custom_components/unfoldedcircle/infrared.py", line 165, in async_send_command
    hex_code = _timings_to_pronto(command.modulation, timings)
  File "/config/custom_components/unfoldedcircle/infrared.py", line 285, in _timings_to_pronto
    on_units = max(1, round(t.high_us / unit_us))
                            ^^^^^^^^^
AttributeError: 'int' object has no attribute 'high_us'

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome, safari
 - Version: 

**Smartphone (please complete the following information):**

**Additional context**
This worked well in 2026.4
I am testing with v1.1.1. I assume v1.1.0 has the same issue.
2026.5 changelog includes a revert of Broadlink IR emitter support (https://github.com/home-assistant/core/pull/168717), which might be related.

I opened a bug report in Home Assistant core repo about this (https://github.com/home-assistant/core/issues/172209). Their answer was:
“Hey @ElBalsero , thanks for reporting this. From the logs you shared, this is an issue with the [Unfolded Circle custom integration](https://github.com/JackJPowell/hass-unfoldedcircle), so I'll ask you to open an issue in the integration's repository.
It looks like it needs to be updated to handle the breaking changes in the infrared-protocols lib, namely the https://github.com/home-assistant-libs/infrared-protocols/pull/19.”

**Comment by JackJPowell** [comment]
Excellent report! Thank you!

Fixed in [release v1.1.2](https://github.com/JackJPowell/hass-unfoldedcircle/releases/tag/v1.1.2)

**Comment by ElBalsero** [comment]
Hey Jack,
Thanks for the new release. I’ve installed and… something weird happens. I’m afraid this report is not as clarifying as the previous.

When pressing the button, the error is not there anymore. However, there’s also no effect in the TV at all. No errors are generated. Not even in debug mode. The UI claims to have sent the command… but nothing happens. 

Things I tried:

To send the same command using unfoldedcircle.send_ir_command: this works perfectly

To remove and reinstall the LG infrared integration: still the same

To add the button press IR command into a script: and this is the weirdest. First time, and only first time that I send the command from inside the script, it kind of kills the connection to the dock and it recycles (see paste below). After that first time, the script would send the commands successfully… but without effect. Honestly… I’m not sure how relevant is this or even if it was happening before.

If there’s any particular test I can do to help, please let me know and I’ll be more than happy to do it.

2026-05-27 19:48:43.649 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Failed to send IR command to dock port 0: 503 Request: SERVICE_UNAVAILABLE Reason: Connection to dock not established
2026-05-27 19:48:43.653 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140118802332096] Error handling message: Failed to send IR command to dock port 0: 503 Request: SERVICE_UNAVAILABLE Reason: Connection to dock not established (home_assistant_error) Daniel from 10.34.43.254 (Mozilla/5.0 (iPad; CPU OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.3 Mobile/15E148 Safari/604.1)
2026-05-27 19:55:53.087 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Failed to send IR command to dock port 0: 503 Request: SERVICE_UNAVAILABLE Reason: Connection to dock not established
2026-05-27 19:55:53.089 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140118802332096] Error handling message: Failed to send IR command to dock port 0: 503 Request: SERVICE_UNAVAILABLE Reason: Connection to dock not established (home_assistant_error) Daniel from 10.34.43.254 (Mozilla/5.0 (iPad; CPU OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.3 Mobile/15E148 Safari/604.1)
2026-05-27 19:56:24.427 WARNING (MainThread) [custom_components.unfoldedcircle.coordinator] Unfolded Circle Remote websocket reconnected - starting full data refresh to resync state
2026-05-27 19:56:24.612 WARNING (MainThread) [custom_components.unfoldedcircle.coordinator] Unfolded Circle Remote full data refresh completed successfully after websocket reconnection

**Comment by JackJPowell** [comment]
The logic to construct the pronto command from the timings is probably slightly off. Let me take another run at it.

**Comment by JackJPowell** [comment]
Would you be able willing and able to update one of the source files in your custom_components directory to test out the change before I make a new release? I'm not able to test myself other than validate the code no longer throws an error. 

If so, copy [infrared.py](https://github.com/JackJPowell/hass-unfoldedcircle/blob/main/custom_components/unfoldedcircle/infrared.py) into your custom_components/unfoldedcircle folder and restart home assistant. Then try to send a command. If the command works, perfect. I'll get a release out right after. 

If it doesn't work, please check your Home Assistant Logs and confirm you see an error message that says "Thank you for testing!" If you don't see that, something about the code update didn't take and you'll need to try again or confirm with me. But based on your reports, I suspect you have a good handle on things :)

**Comment by ElBalsero** [comment]
Yes!!! It works now! Genious.
Probably not relevant anymore, but the "Thank you for testing!" is indeed in the log :-)
Thanks a lot for looking into this and fixing it, man.

**Comment by JackJPowell** [comment]
Wonderful! I just pushed 1.1.3
